#!/bin/bash

# GitHub Pages 部署脚本
# 此脚本将帮助您将项目部署到GitHub并启用GitHub Pages服务

echo "========================================"
echo "任务管理系统 - GitHub Pages 部署脚本"
echo "========================================"

# 检查Git是否已安装
if ! command -v git &> /dev/null; then
    echo "错误: Git未安装，请先安装Git后再尝试。"
    exit 1
fi

# 检查是否已在Git仓库中
if [ ! -d ".git" ]; then
    echo "提示: 当前目录不是Git仓库，需要初始化..."
    
    # 询问GitHub用户名
    read -p "请输入您的GitHub用户名: " github_username
    
    # 询问仓库名称
    read -p "请输入要创建的GitHub仓库名称 (默认为 'task-management-system'): " repo_name
    repo_name=${repo_name:-task-management-system}
    
    # 初始化Git仓库
    echo "正在初始化Git仓库..."
    git init
    
    # 设置用户名和邮箱（使用默认值）
    git config user.name "Task Management System"
    git config user.email "deploy@task-system.example"
    
    # 添加远程仓库
    remote_url="git@github.com:${github_username}/${repo_name}.git"
    echo "正在添加远程仓库: $remote_url"
    git remote add origin "$remote_url"
    
    echo "提示: 您需要先在GitHub上创建仓库 '$repo_name'，然后再继续部署。"
    echo "请访问 https://github.com/new 创建同名仓库，然后重新运行此脚本。"
    exit 1
fi

# 检查远程仓库设置
remote_url=$(git config --get remote.origin.url)
if [ -z "$remote_url" ]; then
    echo "错误: 未设置远程仓库。请先设置GitHub远程仓库。"
    echo "使用命令: git remote add origin git@github.com:您的用户名/仓库名.git"
    exit 1
fi

echo "检测到远程仓库: $remote_url"

# 创建或更新.gitignore文件（如果缺少）
if [ ! -f ".gitignore" ]; then
    echo "正在创建.gitignore文件..."
    cat > .gitignore << 'EOF'
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Dependency directories
node_modules/
jspm_packages/

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional stylelint cache
.stylelintcache

# Mac files
.DS_Store

# Windows files
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db
*.stackdump
[Dd]esktop.ini

# Linux files
*~

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# Browser files
*.browser.*
*.tmp.js

# Testing files
*.test.js
__tests__/

# Local development files
.dev
.local/*

# Environment variables
.env
.env.*
!.env.example
EOF
fi

# 构建部署版本
echo "正在准备部署文件..."

# 检查是否有node_modules目录，如果有则排除
if [ -d "node_modules" ]; then
    echo "检测到node_modules目录，将在.gitignore中排除。"
fi

# 添加所有文件到暂存区
echo "正在添加文件到Git..."
git add .

# 提交更改
echo "正在提交更改..."
git commit -m "部署任务管理系统到GitHub Pages"

# 推送到GitHub
echo "正在推送到GitHub..."
git push -u origin main

# 检查是否需要创建gh-pages分支
echo "正在设置GitHub Pages部署..."
git checkout -b gh-pages 2>/dev/null || git checkout gh-pages
git push origin gh-pages
git checkout main

# 完成提示
echo "========================================"
echo "✅ 部署完成！"
echo "========================================"
echo "请按照以下步骤完成GitHub Pages配置："
echo "1. 访问 https://github.com/您的用户名/仓库名"
echo "2. 点击 'Settings' -> 'Pages'"
echo "3. 在 'Source' 选择 'Deploy from a branch'"
echo "4. 分支选择 'gh-pages'，目录选择 '/'"
echo "5. 点击 'Save'"
echo ""
echo "配置完成后，您的网站将在几分钟后可访问："
echo "https://您的用户名.github.io/仓库名/"
echo ""
echo "其他用户可以通过此URL在不同电脑和网络中访问您的系统！"